from __future__ import annotations

from typing import Any, Mapping
import json


def compile_remotion_scene_spec(doc: Mapping[str, Any]) -> dict[str, Any]:
    target = dict(doc["compiler_targets"]["remotion"])
    project = dict(target["project"])
    shots = {s["id"]: s for s in doc["shots"]}
    scenes = []
    for boundary in target["scene_boundaries"]:
        shot = shots[boundary["shot_id"]]
        events = sorted(shot.get("micro_choreography", []), key=lambda e: (e["at_frame"], e["id"]))
        scenes.append({
            "id": shot["id"],
            "from": boundary["from_frame"],
            "durationInFrames": boundary["to_frame"] - boundary["from_frame"] + 1,
            "camera": shot["camera_plan"],
            "depth": shot["depth_plan"],
            "transition": shot["transition_spec"],
            "events": events,
        })
    return {"project": project, "zOrder": target["z_order"], "scenes": scenes}


def emit_remotion_typescript(doc: Mapping[str, Any], *, const_name: str = "motionSpec") -> str:
    spec = compile_remotion_scene_spec(doc)
    payload = json.dumps(spec, indent=2, ensure_ascii=False)
    return (
        "// Generated by MOTION.OS — deterministic scene contract\n"
        "export type MotionSceneSpec = { project: { fps: number; width: number; height: number; duration_frames: number }; zOrder: string[]; scenes: unknown[] };\n"
        f"export const {const_name}: MotionSceneSpec = {payload} as const;\n"
    )


def validate_scene_coverage(spec: Mapping[str, Any]) -> list[str]:
    errors: list[str] = []
    scenes = sorted(spec.get("scenes", []), key=lambda s: s["from"])
    if not scenes:
        return ["no_scenes"]
    cursor = 0
    for scene in scenes:
        if scene["from"] != cursor:
            errors.append(f"scene_gap_or_overlap:{cursor}->{scene['from']}")
        if scene["durationInFrames"] <= 0:
            errors.append(f"invalid_duration:{scene['id']}")
        cursor = scene["from"] + scene["durationInFrames"]
    total = int(spec["project"]["duration_frames"])
    if cursor != total:
        errors.append(f"duration_mismatch:{cursor}!={total}")
    return errors
