from __future__ import annotations
from typing import Any
STYLE_PROFILES={'editorial_finance':{'palette':['#E7E1D6','#171512','#746F67','#D6D2C8'],'type':'high_contrast_serif + neutral_grotesk','materials':['warm_paper','engraved_metal','matte_ink'],'motion':['technical_grid_draw','hero_object_macro_push','mask_reveal','object_occlusion','parallax_resolve']},'swiss_brutalist':{'palette':['#F4F4F0','#101010','#C6C6C1'],'type':'oversized grotesk + mono microcopy','materials':['matte_paper','flat_ink'],'motion':['grid_snap','hard_mask','type_stack','axis_slide','modular_resolve']},'dark_technical':{'palette':['#0D0F12','#F3F3EF','#6E747C','#A8ADB3'],'type':'condensed grotesk + mono annotation','materials':['charcoal','brushed_metal','glass'],'motion':['scan_reveal','depth_push','vector_trace','glass_occlusion','hud_resolve']},'experimental_kinetic':{'palette':['#EFECE4','#111111','#7B756B'],'type':'display_serif + grotesk','materials':['paper','metal','ink'],'motion':['tracking_converge','type_tunnel','radial_warp','foreground_pass','kinetic_resolve']}}
def normalize_brief(raw:dict[str,Any])->dict[str,Any]:return {'objective':(raw.get('objective') or 'Create a premium motion-graphics piece').strip(),'platform':raw.get('platform','Instagram Reels'),'duration':float(raw.get('duration',10)),'aspect_ratio':raw.get('aspect_ratio','9:16'),'fps':int(raw.get('fps',30)),'headline':(raw.get('headline') or raw.get('copy') or 'MOTION BECOMES SYSTEM').strip(),'supporting':raw.get('supporting','Designed, directed and validated as a system.'),'style':raw.get('style','editorial_finance'),'realism':float(raw.get('realism',.9)),'energy':float(raw.get('energy',.78)),'brand':raw.get('brand',{'name':'MOTION.OS'}),'constraints':raw.get('constraints',['no_people','exact_typography','deterministic_timing'])}
def choose_style(brief):
    name=brief['style'] if brief['style'] in STYLE_PROFILES else 'editorial_finance';return {'style_id':name,**STYLE_PROFILES[name],'vector':{'grid_strength':.88,'negative_space':.56,'depth':.72,'motion_energy':brief['energy'],'realism':brief['realism']}}
def storyboard(brief,style):
    d=brief['duration'];climax='type_tunnel' if style['style_id']=='experimental_kinetic' else 'depth_push';beats=[('hook',0,.14,'technical_grid_draw'),('hero_reveal',.14,.29,'hero_object_macro_push'),('headline_payoff',.29,.43,'mask_reveal'),('transition',.43,.54,'object_occlusion'),('transformation',.54,.72,'parallax_resolve'),('climax',.72,.88,climax),('resolve',.88,1,'final_hold')];return [{'id':f'B{i+1:03d}','function':fn,'start':round(a*d,3),'end':round(b*d,3),'primitive':prim,'priority':10 if fn in ('hook','headline_payoff','resolve') else 7} for i,(fn,a,b,prim) in enumerate(beats)]
def asset_plan(brief,style):return [{'id':'A001','role':'hero_object','type':'procedural_realistic','subject':'engraved_silver_coin','source':'procedural_original','license':'original','alpha':True,'realism_target':brief['realism']},{'id':'A002','role':'paper_texture','type':'procedural','source':'procedural_original','license':'original'},{'id':'A003','role':'technical_overlay','type':'svg_procedural','source':'procedural_original','license':'original'},{'id':'A004','role':'headline','type':'deterministic_text','source':'brief','license':'user_supplied'}]
def render_plan(brief,style,beats):return {'renderer':'native_prototype','preferred_production_renderer':'hyperframes+remotion_hybrid','width':1080,'height':1920,'fps':brief['fps'],'duration':brief['duration'],'beats':beats,'motion_blur':'simulated','deterministic':True}
